export const DEFAULT_IMG_ALT = 'URL detected by the renderer'
export const DEFAULT_NO_WORD = 'No'
export const DEFAULT_YES_WORD = 'Yes'
export const GENERIC_ERROR_MESSAGE = 'Something went wrong !'
export const ORDER_ASC = 'ASC'
export const ORDER_DESC = 'DESC'
export const STR_FALSE = 'false'
export const STR_ZERO = '0'
