# Set update schedule for each package manager
version: 2
updates:
  # Check for updates to GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  # Maintain dependencies for npm packages
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
