name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: |
          corepack enable yarn

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check the typings
        run: yarn type-check

      - name: Execute the tests
        run: yarn test --coverage=false

      - name: Build the library and the example
        run: yarn prd
