# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14 (LTS)
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Execute the tests
        run: yarn test --coverage=false
      - name: Build the library and the example
        run: yarn prd
